apiVersion: v2
kind: PersistentVolume
metadata:
  name: redis-leader-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: tkgs-storage-class-name
